(define (make-monitored f pass)
  (define init 0)
  (define (count) init)
  (define (call n)
    (set! init (+ init 1))
    (f n))
  (define (exec m p)
    (if (eq? p pass)
      (cond ((eq? m 'how-many-calls?) (count))
            ((eq? m 'reset-count) (set! init 0))
            (else (call m)))
      "Incorrect password"))
  exec)

