(define (make-count balance password)
  (define (error-count 0))
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (error m)
    "wrong password")
  (define (call-110 m)
    "call 110")
  (define (dispatch p m)
    (if (eq? p password)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else "error request"))
      (begin (set! error-count (+ error-count 1))
             (if (= error-count 7)
               call-110
               error))))
  dispatch)

