(define (install-eval)
  (put 'define eval-definition)
  (put 'quote (lambda (exp env) (text-of-quotation exp)))
  (put 'set! eval-assignment)
  (put 'define eval-definition)
  (put 'if eval-if)
  (put 'lambda (lambda (exp env)
                 (make-procedure (lambda-parameters exp)
                                 (lambda-body exp)
                                 env)))
  (put 'begin (lambda (exp env)
                (eval-sequence (begin-actions exp) env)))
  (put 'cond (lambda (exp env)
               (eval (cond->if exp) env))))

